### ISSUE TITLE
Waku Template feedback

### ISSUE THREAD

**Issue by fryorcraken** [acid-info/logos-docusaurus-plugins#7]
Look at `staging` branch of https://github.org/waku-org/waku.guide

1. Discord invite link is incorrect

Discord invite link at the bottom of the page is prefixed by `https://discordapp.com/users` instead of `https://discord.gg`

2. Missing "Waku" Logo/such title:

See top left corner. Feels empty/something missing. No Waku title and nothing happens when clicking on Waku Logo

![image](https://user-images.githubusercontent.com/110212804/221761032-80526fdd-625a-48fa-ae00-9c0654f38df9.png)

3. How to enable multi-language dropdown?

I want to start adding JavaScript doc to waku.guide, how do I proceed?

**Comment by amirhouieh** [comment]
@fryorcraken moving this issue here. 
This theme on skin and UI design did not get approval and so we might not be using it. For now, I suggest either use the Docusourius default theme, and later on, we can easily migrate the content to our own theme. Or use this theme but then ignore the design issues until the new theme is built.

**Comment by fryorcraken** [comment]
FYI @LordGhostX we can are free to use Docusaurus own theme on docs website.
